spring.application.name=product-service
server.port=8081
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
app.jwt.issuer=${JWT_ISSUER}
app.jwt.key-id=${JWT_KEY_ID}
app.jwt.public-key=${JWT_PUBLIC_KEY}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER}
auth-server.base-url=${AUTH_SERVER_BASE_URL}
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}